/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RetoSemana4;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author linam
 */
public class ActualizarEliminarEmpleadoFrame extends javax.swing.JFrame {
    ArrayList<Empleado> vEmpleado = new ArrayList<>();

    /**
     * Creates new form ActualizarEliminarEmpleadoFrame
     */
    public ActualizarEliminarEmpleadoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jCheckBoxProveedor = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jButtonEliminarEmpleados = new javax.swing.JButton();
        jTextFieldSalario = new javax.swing.JTextField();
        jButtonActualizarEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleado: idEmpleado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(145, 30, 200, 20);

        jLabel2.setText("Nombre*");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 50, 20);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 70, 50, 20);
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(30, 95, 200, 30);
        getContentPane().add(jTextFieldApellido);
        jTextFieldApellido.setBounds(260, 95, 200, 30);

        jLabel4.setText("Correo*");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 50, 20);

        jLabel5.setText("Celular*");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 140, 50, 20);
        getContentPane().add(jTextFieldCorreo);
        jTextFieldCorreo.setBounds(30, 165, 200, 30);
        getContentPane().add(jTextFieldCelular);
        jTextFieldCelular.setBounds(260, 165, 200, 30);

        jLabel6.setText("Salario*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 210, 50, 20);
        getContentPane().add(jTextFieldCargo);
        jTextFieldCargo.setBounds(30, 305, 200, 30);

        jCheckBoxProveedor.setText("Proveedor");
        getContentPane().add(jCheckBoxProveedor);
        jCheckBoxProveedor.setBounds(30, 210, 200, 20);

        jLabel7.setText("Cargo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 50, 20);

        jButtonEliminarEmpleados.setText("Eliminar Empleados");
        jButtonEliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarEmpleados);
        jButtonEliminarEmpleados.setBounds(260, 355, 200, 30);
        getContentPane().add(jTextFieldSalario);
        jTextFieldSalario.setBounds(260, 235, 200, 30);

        jButtonActualizarEmpleados.setText("Actualizar Empleados");
        jButtonActualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActualizarEmpleados);
        jButtonActualizarEmpleados.setBounds(30, 355, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEmpleadosActionPerformed
        Empleado emps = new Empleado();
        String proveedor="";

        emps.setNombre(jTextFieldNombre.getText());
        emps.setApellido(jTextFieldApellido.getText());
        emps.setCorreo(jTextFieldCorreo.getText());
        emps.setCelular(jTextFieldCelular.getText());
        if (jCheckBoxProveedor.isSelected()){
            proveedor = "Proveedor";
        }
        emps.setSalario(Integer.parseInt(jTextFieldSalario.getText()));
        emps.setCargo(jTextFieldCargo.getText());

        vEmpleado.add(emps);
        JOptionPane.showMessageDialog(this, "Empleado Creado");
        System.out.println("Empleado Creado");

    }//GEN-LAST:event_jButtonEliminarEmpleadosActionPerformed

    private void jButtonActualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarEliminarEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarEliminarEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarEliminarEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarEliminarEmpleadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarEliminarEmpleadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarEmpleados;
    private javax.swing.JButton jButtonEliminarEmpleados;
    private javax.swing.JCheckBox jCheckBoxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
